services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
      container_name: glific-backend
      build:
        dockerfile: Dockerfile

      environment:
         # Variables to connect to our Postgres server.
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: glific_dev
         PGPORT: 5432
         PGHOST: postgres
      ports:
      - 4000:4000
      depends_on:
      - postgres



volumes:
  pgdata:
